In [2]:
import pandas as pd 
import numpy as np

In [3]:
df = pd.read_csv('spacenet.csv')
df2 = pd.read_csv('new-laptop.csv')
df3 = pd.read_csv('laptopSy.csv')
df4  =pd.read_csv('afandyAndSpahi.csv')

# Column Names Fix 
every df need to fix its name

In [4]:
df.columns

Index(['brand  ', 'model                              ',
       'cpu                        ', 'ram       ', 'hard              ',
       'gpu                     ', 'new ', 'price ', 'source'],
      dtype='object')

In [5]:
def columnsStriper(df):
    for col in df.columns:
        df.rename(columns={col: col.strip()}, inplace=True)

In [6]:
# Note : strip == trim
columnsStriper(df)
columnsStriper(df2)
columnsStriper(df3)
columnsStriper(df4)

In [7]:
df.columns

Index(['brand', 'model', 'cpu', 'ram', 'hard', 'gpu', 'new', 'price',
       'source'],
      dtype='object')

In [8]:
new = pd.concat([df, df2, df3, df4], ignore_index=True)

In [9]:
new.shape

(331, 9)

In [10]:
new.head()

,brand,model,cpu,ram,hard,gpu,new,price,source
0,ASUS,ASUS Vivobook E1504G,Intel Core i3‑N305,8GB DDR4,256GB SSD NVMe,Intel UHD Graphics,true,335,spacenet
1,ASUS,ASUS VivoBook 15 X1504VA‑NJ739,Intel Core i3‑1315U,8GB DDR4,512GB SSD NVMe,Intel UHD Graphics,true,360,spacenet
2,ASUS,ASUS ExpertBook,Intel Core i3‑1315U,8GB DDR5,256GB SSD NVMe,Intel UHD Graphics,true,355,spacenet
3,ASUS,ASUS Vivobook X1404V,AMD Ryzen 7 7445HS,16GB DDR5,512GB SSD NVMe,NVIDIA RTX 4050 6GB,true,465,spacenet
4,ASUS,ASUS Vivobook 15 X1504VA‑NJ104,Intel Core i5‑1335U,8GB DDR4,512GB SSD NVMe,Intel UHD Graphics,true,465,spacenet

In [10]:
new.tail()

,brand,model,cpu,ram,hard,gpu,new,price,source
326,Lenovo,LOQ 15IAX9E,Core™ i7 12650HX,16GB DDR5,512 GB SSD,RTX™ 4050,True,840,afandyAndSpahi
327,Dell,Vostro 3530,Intel Core i5 1334U,8GB DDR4 2666 Mhz,NVME 512GB SSD,Anti-glare,True,470,afandyAndSpahi
328,HP,NaN,Intel® Core™ i5-1334U,NaN,NaN,NVIDIA® GeForce® MX570 2G,False,560,afandyAndSpahi
329,Lenovo,NaN,Intel i5-13420H,NaN,NaN,Anti-glare,False,480,afandyAndSpahi
330,HP,15-FB2082WM,AMD Ryzen 5,NaN,NaN,NVIDIA RTX4050 6GB DDR6,False,775,afandyAndSpahi

In [11]:
new.isna().sum()

brand     0
model     2
cpu       0
ram       3
hard      4
gpu       1
new       0
price     0
source    0
dtype: int64

In [12]:
new[new['hard'].isna()]

,brand,model,cpu,ram,hard,gpu,new,price,source
324,MICROSOFT,Surface Pro 3,Core™ i7,8GB,NaN,NaN,False,200,afandyAndSpahi
328,HP,NaN,Intel® Core™ i5-1334U,NaN,NaN,NVIDIA® GeForce® MX570 2G,False,560,afandyAndSpahi
329,Lenovo,NaN,Intel i5-13420H,NaN,NaN,Anti-glare,False,480,afandyAndSpahi
330,HP,15-FB2082WM,AMD Ryzen 5,NaN,NaN,NVIDIA RTX4050 6GB DDR6,False,775,afandyAndSpahi

In [13]:
#Handle Here.

In [14]:
new.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 331 entries, 0 to 330
Data columns (total 9 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   brand   331 non-null    object
 1   model   329 non-null    object
 2   cpu     331 non-null    object
 3   ram     328 non-null    object
 4   hard    327 non-null    object
 5   gpu     330 non-null    object
 6   new     331 non-null    object
 7   price   331 non-null    int64
 8   source  331 non-null    object
dtypes: int64(1), object(8)
memory usage: 23.4+ KB

In [15]:
new['brand'].value_counts()

brand
Lenovo       76
ASUS         54
HP           27
Lenovo       22
Asus         22
HP           20
DELL         14
Dell         13
HP           12
Lenovo       11
Asus         11
DELL          9
Apple         6
MSI           6
LENOVO        5
Acer          4
DELL          4
Acer          3
LENOVO        2
Dell          2
Acer          1
TOSHIBA       1
Hp            1
ASUS          1
hp            1
Toshiba       1
Apple         1
MICROSOFT     1
Name: count, dtype: int64

# Handling brand

In [16]:
new['brand'] = new['brand'].str.strip().str.upper()

brand_map = {
    "LENOVO":"Lenovo",
    "Asus":"ASUS",
    "DELL":"Dell",
    "HP":"hp",
    "TOSHIBA":"Toshiba",
    "MICROSOFT":"Microsoft"
}

In [ ]:
new['brand'] = new['brand'].replace(brand_map)
new['brand'].value_counts()

brand
Lenovo       116
ASUS          88
hp            61
Dell          42
ACER           8
APPLE          7
MSI            6
Toshiba        2
Microsoft      1
Name: count, dtype: int64

# CPU Handling

Note: first section is cleaning on the df only the rest of CPU Handling section is for the new dataFrame

In [18]:
import re

In [19]:
new['cpu'].value_counts()

cpu
Intel® Core™ i7-13620H                                                      10
Intel® Core™ i5-13420H                                                       8
Intel® Core™ i3-1315U                                                        6
Intel Core i5-13420H                                                         6
Intel® Core™ i7-13650HX                                                      5
                                                                            ..
Core™ i7 12650HX                                                             1
Intel Core i5 1334U                                                          1
Intel® Core™ i5-1334U                                                        1
Intel i5-13420H                                                              1
AMD Ryzen 5                                                                  1
Name: count, Length: 202, dtype: int64

In [ ]:
new['cpu'] = (
    new['cpu']
    .str.replace('®', '', regex=False)
    .str.replace('™', '', regex=False)
    .str.replace(r'[^A-Za-z0-9\s]', ' ', regex=True)
    .str.replace(r'\s+', ' ', regex=True)
    .str.strip()
)
new['cpu'].value_counts()

cpu
Intel Core i5 13420H        19
Intel Core i7 13620H        15
Intel Core i7 13650HX       11
Intel Core i3 1315U         10
Intel Core Ultra 9 275HX     9
                            ..
Intel Core i7 4th Gen        1
Core i7                      1
Core i7 12650HX              1
Intel i5 13420H              1
AMD Ryzen 5                  1
Name: count, Length: 152, dtype: int64

In [21]:
cpus = df['cpu'].copy()
x = re.search(r'Intel|AMD*', cpus[0])
if x:
    print(x[0])
else:
    print(x)

Intel

In [22]:
# extracting left side of cpu (intel/amd)   

def a(x):
    test = re.search(r'Intel|AMD|Snapdragon|Celeron *', x)
    if test:
        return test[0]
    else:
        return test
lCpu = cpus.apply(lambda x: a(x))
lCpu.head()

0    Intel
1    Intel
2    Intel
3      AMD
4    Intel
Name: cpu, dtype: object

In [23]:
lCpu[lCpu.isna()]

Series([], Name: cpu, dtype: object)

In [24]:
df['cpu'][32]

'Celeron N4500              '

In [25]:
# extracting left side of cpu (intel/amd)   /Snapdragon, Celeron , Apple
def a(x):
    test = re.search(r'Intel|AMD|Snapdragon|Celeron|Apple*', x)
    if test:
        return test[0]
    else:
        return test
lCpu = cpus.apply(lambda x: a(x))
print("num of nulls is ... ", lCpu.isna().sum())
lCpu.head(6)

num of nulls is ...  0

0         Intel
1         Intel
2         Intel
3           AMD
4         Intel
5    Snapdragon
Name: cpu, dtype: object

In [26]:
df['cpu'].head()

0    Intel Core i3‑N305
1    Intel Core i3‑1315U
2    Intel Core i3‑1315U
3    AMD Ryzen 7 7445HS
4    Intel Core i5‑1335U
Name: cpu, dtype: object

In [27]:
def middle(x):
    test = re.search(r'i\d{1}|Ryzen \d{1}|Ultra \d{1}|Core \d{1}|X Plus|N4500', x)
    if(test):
        return test[0]
    else:
        return test
mCpu = cpus.apply(lambda x: middle(x))
print("num of nulls is ... ", mCpu.isna().sum())
mCpu.head(6)

num of nulls is ...  0

0         i3
1         i3
2         i3
3    Ryzen 7
4         i5
5     X Plus
Name: cpu, dtype: object

In [28]:
cpus[mCpu[mCpu.isna()].index]

Series([], Name: cpu, dtype: object)

In [29]:
mCpu.value_counts()

cpu
i7         17
i5         12
i3          7
Ryzen 7     6
Ryzen 9     4
i9          3
Core 5      3
Ultra 9     3
Ryzen 5     2
X Plus      1
Core 7      1
N4500       1
Name: count, dtype: int64

In [30]:
cpus.tail()

55    Intel Core i5‑13500H
56    Intel Core i9‑13900H
57    Intel Core i7‑14650HX
58    Intel Core i5‑13420H
59    Intel Core i7‑12420H
Name: cpu, dtype: object

In [31]:
cpus = cpus.replace(r'\W', ' ', regex=True)
cpus.value_counts()

cpu
Intel Core i5 13420H           5
Intel Core i3 1315U            4
Intel i7 14650HX               4
Intel Core i7 13650HX          4
AMD Ryzen 7 7445HS             3
Intel Core i3 N305             3
Intel Core i9 14900HX          2
AMD Ryzen 9 8940HX             2
Intel Core i5 13450HX          2
Intel Ultra 9 275HX            2
Intel Core 5 210H              2
Intel Core i7 1355U            1
Intel Core i5 1335U            1
Snapdragon X Plus X1P42100     1
AMD Ryzen 9 720                1
AMD Ryzen 9 9955HX             1
Intel Core i5 1334U            1
Intel Core i5  13th Gen        1
Intel Core 5 120U              1
Intel Core 7 150U              1
Intel i7 13620H                1
AMD Ryzen 7 7435HS             1
AMD Ryzen 5 7520U              1
Celeron N4500                  1
AMD Ryzen 5 7235HS             1
Intel Core i7 13420H           1
Intel Core i5 12450HX          1
Intel Core i7 12650HX          1
Intel Core i7 13450HX          1
Intel Core i7 13700HX          1
AMD Ryzen 7 250                1
AMD Ryzen 7 260                1
Intel Core i7 14700HX          1
Intel Core Ultra 9 275HX       1
Intel Core i5 13500H           1
Intel Core i9 13900H           1
Intel Core i7 14650HX          1
Intel Core i7 12420H           1
Name: count, dtype: int64

In [32]:
# (?<=B)A
"""
Middls:
i7         17
i5         12
i3          7
Ryzen 7     6
Ryzen 9     4
i9          3
Core 5      3
Ultra 9     3
Ryzen 5     2
X Plus      1
Core 7      1
N4500       1
""" 

def right(x):
    test = re.search(r'(?<=i\d{1} )[A-Za-z0-9]*|(?<=Ryzen \d{1} )[A-Za-z0-9]*|(?<=Core \d{1} )[A-Za-z0-9]*|(?<=Ultra \d{1} )[A-Za-z0-9]*|(?<=X Plus )[A-Za-z0-9]*|Celeron [A-Za-z0-9]* ', x)
    if test:
        return test[0]
    else:
        return test
rCpu = cpus.apply(lambda x: right(x))
print("num of nulls is... ", rCpu.isna().sum())
rCpu.value_counts()

num of nulls is...  0

cpu
13420H            6
14650HX           5
13650HX           4
1315U             4
N305              3
7445HS            3
275HX             3
13450HX           3
8940HX            2
210H              2
14900HX           2
13620H            1
X1P42100          1
9955HX            1
720               1
7435HS            1
1355U             1
1335U             1
120U              1
1334U             1
                  1
Celeron N4500     1
7520U             1
7235HS            1
12450HX           1
150U              1
12650HX           1
13700HX           1
250               1
260               1
14700HX           1
13500H            1
13900H            1
12420H            1
Name: count, dtype: int64

In [33]:
cpus[rCpu[rCpu.isna()].index]

Series([], Name: cpu, dtype: object)

In [34]:
df2['cpu'].value_counts()

cpu
Intel® Core™ i7-13620H                    10
Intel® Core™ i5-13420H                     8
Intel® Core™ i3-1315U                      6
Intel® Core™ i7-13650HX                    5
Intel® Core™ i7 processor 14650HX          5
ntel® Core™ i5-13450HX                     4
AMD Ryzen™ 7 7435HS                        4
Intel® Core™ Ultra 9  275HX                4
AMD Ryzen™ 7 7445HS                        3
AMD Ryzen™ 7-5800H                         3
Intel® Core™ i7-1355U                      3
Intel® Core™ Ultra 5 125U                  3
Intel® Core™ Ultra 7 256V                  2
AMD Ryzen™ 5 7520U                         2
Intel® Core™ i3-N305                       2
AMD Ryzen™ 7 250                           2
Intel® Core™ i9-13900H                     2
Intel Core™ i5-10210U                      2
Intel Core™ i3-1305U                       2
AMD Ryzen™ 5 7235HS                        2
Intel® Core™ Ultra 7 255H                  2
Intel® Core™ i9 14900HX                    2
Intel® Core™ i5-1334U                      2
Intel® Core™ 7 150U                        2
AMD Ryzen™ 9 8945HS                        2
Intel® Core™ 7 Processor 240H              2
Intel® Core™ Ultra 9 185H                  2
Intel® Core™ Ultra 5 Processor 226V        1
Intel® Core™ i7-1165G7                     1
Intel® Core™ Ultra 7 255U                  1
Intel® Core™ Ultra 5 225U                  1
Intel® Core™ i7 14700HX                    1
Intel® Core™ 5 120U                        1
AMD Ryzen™ 9 6900HX                        1
Intel Celeron N4500                        1
AMD Ryzen™ 9 9955HX                        1
Intel Core i5-10500H                       1
Intel® Core™ i7-11800H                     1
Intel Processor N100                       1
Qualcomm Snapdragon X Plus X1P-42-100      1
AMD Ryzen™ 7 7260                          1
AMD Ryzen™ 7 7840HS                        1
AMD Ryzen™ 3 7320U                         1
Intel® Core™ i5-12600HX                    1
Intel® Core™ i7-12650HX                    1
Intel® Core™ i5-12450HX                    1
Intel® Core™ i5-1335U                      1
Ryzen 7 3700U                              1
Name: count, dtype: int64

NOTE: From here we end handling the df (DataFrame) and
start in the second section (new DataFrame handling) 
the rest of code is handling the new DataFrame (new: df & df2 & df3 & df4)

In [35]:
cpuTest = new['cpu']
lTest = cpuTest.apply(lambda x: a(x))
mTest = cpuTest.apply(lambda x: middle(x))
rTest = cpuTest.apply(lambda x: right(x))

In [36]:
print(lTest.isna().sum())
print('='*10)
print(mTest.isna().sum())
print('='*10)
print(rTest.isna().sum())

41
==========
25
==========
30

In [37]:
new['cpu'][lTest[lTest.isna()].index]

74               ntel Core i5 13450HX
101              ntel Core i5 13450HX
105              ntel Core i5 13450HX
140              ntel Core i5 13450HX
159                     Ryzen 7 3700U
169       intel core i5 9400H 2 50ghz
170        intel XEON E 2276M 2 80ghz
171       intel core i7 9850H 2 60ghz
172       intel core i7 8850H 2 60ghz
173      intel core i7 6820HQ 2 70ghz
175       intel core i7 9750H 2 60ghz
177       intel core i7 6500U 2 50ghz
178       intel core i5 6200U 2 30GHz
180      intel core i5 6300HQ 2 30GHZ
181       intel CORE I7 6600U 2 60ghz
182      intel core i5 73000U 2 60ghz
183       INTEL CELERON 3865U 1 80GHZ
189      intel core i3 10110U 2 10GHZ
205       intel core i5 8265U 1 60GHZ
206       intel core i5 6200U 2 30GHz
207       intel core i3 6100U 2 30GHZ
208      intel core i7 10875H 2 30GHZ
217       intel core i5 9400H 2 40GHZ
249    inintel core i7 10850H 2 70ghz
252       intel core i5 2450M 2 50ghz
253      intel core i7 6820HQ 2 70ghz
254              intel core i5 1035G1
255      intel core i5 10210U 1 60ghz
259      intel core i7 6820HQ 2 70ghz
264                 intel core 5 210H
273                     Ryzen 5 7520U
274                 intel core 5 120U
285                     Ultra 9 275HX
287                Core Ultra 9 275HX
293                 intel core 5 120U
298               Xeon E3 1545M 1545M
309                      Ultra 9 285H
313                       Ryzen 7 260
316                       Ryzen 7 260
324                           Core i7
326                   Core i7 12650HX
Name: cpu, dtype: object

In [38]:
############################TTTTTTTTTTTTTTTTTTTEEEEEEEEEEEEEEEEEESSSSSSSSSSSSSSSSSTTTTTTTTTTTTTTTTTTTTT
# extracting left side of cpu (intel/amd)   /Snapdragon, Celeron , Apple
def a2(x):
    test = re.search(r'intel|amd|snapdragon|celeron|apple*', x)
    if test:
        return test[0]
    else:
        return test

cpuTest2 = new['cpu'].str.lower()
lTest2 = cpuTest2.apply(lambda x: a2(x))
lTest2.isna().sum()

np.int64(14)

In [39]:
new['cpu'][lTest2[lTest2.isna()].index]

74     ntel Core i5 13450HX
101    ntel Core i5 13450HX
105    ntel Core i5 13450HX
140    ntel Core i5 13450HX
159           Ryzen 7 3700U
273           Ryzen 5 7520U
285           Ultra 9 275HX
287      Core Ultra 9 275HX
298     Xeon E3 1545M 1545M
309            Ultra 9 285H
313             Ryzen 7 260
316             Ryzen 7 260
324                 Core i7
326         Core i7 12650HX
Name: cpu, dtype: object

The following function is the Final function for extracting the cpu brand.

In [40]:
## Final function for extracting the cpu brand
def extract_cpu_brand(x):   
    brand_keywords = {
        "intel": ["core", "ultra", "xeon", "intel"],
        "amd": ["ryzen", "athlon", "amd"],
        "snapdragon": ["snapdragon"],
        "celeron": ["celeron"],
        "apple": ["m1", "m2", "m3", "m4"]
    }
    x = x.lower()
    for brand, keywords in brand_keywords.items():
        if any(keyword in x for keyword in keywords):
            return brand
    return None
cpuBrand = cpuTest2.apply(lambda x: a2(x))
new['cpu'][cpuBrand[cpuBrand.isna()].index]

74     ntel Core i5 13450HX
101    ntel Core i5 13450HX
105    ntel Core i5 13450HX
140    ntel Core i5 13450HX
159           Ryzen 7 3700U
273           Ryzen 5 7520U
285           Ultra 9 275HX
287      Core Ultra 9 275HX
298     Xeon E3 1545M 1545M
309            Ultra 9 285H
313             Ryzen 7 260
316             Ryzen 7 260
324                 Core i7
326         Core i7 12650HX
Name: cpu, dtype: object

In [41]:
new['cpu'][lTest2[lTest2.isna()].index]

74     ntel Core i5 13450HX
101    ntel Core i5 13450HX
105    ntel Core i5 13450HX
140    ntel Core i5 13450HX
159           Ryzen 7 3700U
273           Ryzen 5 7520U
285           Ultra 9 275HX
287      Core Ultra 9 275HX
298     Xeon E3 1545M 1545M
309            Ultra 9 285H
313             Ryzen 7 260
316             Ryzen 7 260
324                 Core i7
326         Core i7 12650HX
Name: cpu, dtype: object

In [42]:
new['cpu'][mTest[mTest.isna()].index]

98                        Intel Processor N100
170                 intel XEON E 2276M 2 80ghz
174                  AMD RYZEN 7 3700U 2 30GHZ
176              AMD RYZEN 5 PRO 4650U 2 10GHZ
179                  AMD RYZEN 3 4300U 2 70GHZ
181                intel CORE I7 6600U 2 60ghz
183                INTEL CELERON 3865U 1 80GHZ
204                     AMD A6 PRO 7050 2 2GHZ
212                    Intel Core ultra 5 225U
221                    AMD Athlon Silver 7120U
225                  AMD RYZEN 5 3500U 2 10GHZ
227            Apple M2 8 Core CPU 10 Core GPU
228            Apple M3 8 Core CPU 10 Core GPU
229            Apple M2 8 Core CPU 10 Core GPU
230    Apple M1 Pro 8 Core CPU 6 2 14 Core GPU
231                       Apple M1 8 4 4 8 GPU
233                      Intel Core I7 13650HX
244                         AMD A8 6410 2 0GHZ
245                      AMD A10 5750M 2 50GHZ
256                      Intel Core I7 13650HX
260                            Intel atom N475
264                          intel core 5 210H
274                          intel core 5 120U
293                          intel core 5 120U
298                        Xeon E3 1545M 1545M
Name: cpu, dtype: object

In [43]:
def middle2(x):
    test = re.search(r'i\d{1}|ryzen \d{1}|ultra \d{1}|core \d{1}|x plus|n\d{3,4}|m\d{1}|a\d{1}|atom|a\d{1} [a-z]{3}|celeron|xeon|athlon\s*\w*', x)
    if(test):
        return test[0]
    else:
        return test

cpuTier = cpuTest2.apply(lambda x: middle2(x))
new['cpu'][cpuTier[cpuTier.isna()].index]

Series([], Name: cpu, dtype: object)

In [44]:
cpuTier.value_counts()

cpu
i7               106
i5                68
ryzen 7           27
i3                25
ultra 9           16
i9                11
core 7            11
ryzen 5           11
ryzen 9            9
core 5             9
ultra 5            8
ultra 7            7
celeron            4
x plus             2
ryzen 3            2
xeon               2
core 3             2
m2                 2
m1                 2
n100               1
athlon silver      1
a6                 1
m3                 1
a8                 1
a1                 1
atom               1
Name: count, dtype: int64

In [45]:
"""def right2(x):
    if not x:
        return None

    x = x.lower()

    # Apple chips
    match = re.search(r'm\d(\s?(pro|max|ultra))?', x)
    if match:
        return match.group(0)

    # N-series (N100)
    match = re.search(r'[a-z]\d{3,4}', x)
    if match:
        return match.group(0)

    # normal CPUs
    match = re.search(r'\d{3,5}[a-z]{0,2}', x)
    if match:
        return match.group(0)

    return None"""

def right2(x):
    if not x:
        return None

    x = x.lower()

    # Apple
    match = re.search(r'm\d(\s?(pro|max|ultra))?', x)
    if match:
        return match.group(0)

    # model + suffix (13620H, 14650HX...)
    match = re.search(r'\b\d{3,5}[a-z]{0,2}\b', x)
    if match:
        return match.group(0)

    # N-series (N100)
    match = re.search(r'\b[a-z]\d{3,4}\b', x)
    if match:
        return match.group(0)

    return None

rTest2 = cpuTest2.apply(lambda x: right2(x))
print("nym of nan is ... ", rTest2.isna().sum())
new['cpu'][rTest2[rTest2.isna()].index].value_counts()

nym of nan is ...  39

cpu
Intel Core i7 14th Generation    5
Intel Core i7 13th Generation    4
Intel Core i7 10th Generation    3
Intel Core i7 9th Generation     3
Intel Core i9 13th Generation    2
Intel Core i5 8th Gen            2
Intel Core i7 7th Generation     2
Intel Core i7 8th Generation     2
Snapdragon X Plus X1P42100       1
Intel Core i5 13th Gen           1
Intel Core i7 1165G7             1
intel core i5 1035G1             1
Intel Core i5 8th Generation     1
Intel Core i7 1185G7             1
Intel Core i7 11th Generation    1
Intel Core i5 1135G7             1
Intel Core i5 10th Generation    1
Intel Core i3 13th Generation    1
Intel Core i5 13th Generation    1
Intel Core i5 1145G7             1
Intel Core i3 13th Gen           1
Intel Core i7 4th Gen            1
Core i7                          1
AMD Ryzen 5                      1
Name: count, dtype: int64

In [46]:
rTest2.value_counts()

cpu
13420h     21
13620h     16
14650hx    14
275hx      13
13650hx    13
           ..
1545m       1
520m        1
285h        1
4260        1
3561        1
Name: count, Length: 100, dtype: int64

In [47]:
def extract_model(x):
    if not x:
        return 0

    x = x.lower()

    #  Apple
    match = re.search(r'm(\d)', x)
    if match:
        return int(match.group(1))

    #  أي رقم 3-5 digits (حتى لو ملتصق)
    match = re.search(r'(\d{3,5})', x)
    if match:
        return int(match.group(1))

    return 0



cpuModel = cpuTest2.apply(lambda x: extract_model(x))
print("nym of nan is ... ", cpuModel.isna().sum())
len(new['cpu'][cpuModel[cpuModel == 0].index])

nym of nan is ...  0

33

In [48]:
cpuModel.value_counts()

cpu
0        33
13420    21
13620    16
14650    14
275      13
         ..
520       1
285       1
4260      1
3561      1
1145      1
Name: count, Length: 101, dtype: int64

In [49]:
def extract_suffix(x):
    if not x:
        return "unknown"

    x = x.lower()

    # Apple tiers
    match = re.search(r'\b(pro|max|ultra)\b', x)
    if match:
        return match.group(1)

    # Intel G-series (G1, G7...)
    match = re.search(r'\d{3,5}(g\d)', x)
    if match:
        return match.group(1)

    # Intel/AMD normal suffix (H / HX / U / P ...)
    match = re.search(r'\d{3,5}([a-z]{1,2})\b', x)
    if match:
        return match.group(1)

    return "unknown"

cpuSuffix = cpuTest2.apply(lambda x: extract_suffix(x))
print(cpuSuffix.value_counts())
new['cpu'][cpuSuffix[cpuSuffix == "unknown"].index].value_counts()

cpu
u          78
h          65
unknown    64
hx         57
ultra      31
hs         17
m           5
hq          5
g7          4
pro         3
hk          1
g1          1
Name: count, dtype: int64

cpu
Intel Core i3 N305                       8
Intel Core i7 14th Generation            5
Intel Core i7 13th Generation            4
Intel Core i7 9th Generation             3
Intel Core i7 10th Generation            3
AMD Ryzen 7 250                          3
Intel Core i9 13th Generation            2
Intel Core i7 7th Generation             2
Intel Core i5 8th Gen                    2
Intel Core i7 8th Generation             2
Apple M2 8 Core CPU 10 Core GPU          2
AMD Ryzen 7 260                          2
Intel Celeron N4500                      2
Ryzen 7 260                              2
Snapdragon X Plus X1P42100               1
AMD Ryzen 9 720                          1
Intel Core i5 13th Gen                   1
AMD Ryzen 7 7260                         1
Celeron N4500                            1
Qualcomm Snapdragon X Plus X1P 42 100    1
Apple M3 8 Core CPU 10 Core GPU          1
Apple M1 8 4 4 8 GPU                     1
AMD A8 6410 2 0GHZ                       1
Intel atom N475                          1
Intel Processor N100                     1
Intel Core i5 8th Generation             1
Intel Core i5 10th Generation            1
Intel Core i7 11th Generation            1
Intel Core i5 4260                       1
Intel Core i3 13th Generation            1
Intel Core i5 13th Generation            1
Intel Core i7 3561                       1
Intel Core i3 13th Gen                   1
Intel Core i7 4th Gen                    1
Core i7                                  1
AMD Ryzen 5                              1
Name: count, dtype: int64

In [50]:
cpuSuffix.value_counts()

cpu
u          78
h          65
unknown    64
hx         57
ultra      31
hs         17
m           5
hq          5
g7          4
pro         3
hk          1
g1          1
Name: count, dtype: int64

In [51]:
def extract_generation(x):
    if not x:
        return 0

    x = x.lower()

    # explicit generation (14th / 10th ...)
    match = re.search(r'(\d{1,2})(st|nd|rd|th)', x)
    if match:
        return int(match.group(1))

    # Apple
    match = re.search(r'\bm(\d)\b', x)
    if match:
        return int(match.group(1))

    return 0

genTest2 = cpuTest2.apply(lambda x: extract_generation(x))
print(genTest2.value_counts())
new['cpu'][genTest2[genTest2 == 0].index].value_counts()

cpu
0     294
13     10
8       5
14      5
10      4
9       3
7       2
2       2
1       2
3       1
11      1
12      1
4       1
Name: count, dtype: int64

cpu
Intel Core i5 13420H        19
Intel Core i7 13620H        15
Intel Core i7 13650HX       11
Intel Core i3 1315U         10
Intel Core Ultra 9 275HX     9
                            ..
Intel Core i7 6600U          1
Core i7                      1
Core i7 12650HX              1
Intel i5 13420H              1
AMD Ryzen 5                  1
Name: count, Length: 131, dtype: int64

In [52]:
"""
TODO:Don't merge apple and intel cpus in same scaller for ML 
Apple: (M1, M2..), intel(i5 9750...)رح يصير في مشاكل بالجيل 
"""

"\nTODO:Don't merge apple and intel cpus in same scaller for ML \nApple: (M1, M2..), intel(i5 9750...)رح يصير في مشاكل بالجيل \n"

In [53]:
# final extractions for cpu
print(cpuBrand.head(1))
print(cpuTier.head(1))
print(cpuModel.head(1))
print(cpuSuffix.head(2))

0    intel
Name: cpu, dtype: object
0    i3
Name: cpu, dtype: object
0    305
Name: cpu, dtype: int64
0    unknown
1          u
Name: cpu, dtype: object

In [54]:
rTest2[0]

'n305'

# GPU handling

In [55]:
new['gpu'].value_counts()

gpu
Intel UHD Graphics                                                                                                         25
Intel UHD Graphics                                                                                                         18
Integrated, Intel® UHD Graphics                                                                                            13
Integrated                                                                                                                 12
NVIDIA RTX 4050 6GB                                                                                                        11
                                                                                                                           ..
NVIDIA GeForce RTX 3050 / Intel UHD Graphics                                                                                1
Intel UHD Graphics 620                                                                                                      1
RTX™ 4050                                                                                                                   1
NVIDIA® GeForce® MX570 2G                                                                                                   1
NVIDIA RTX4050 6GB DDR6                                                                                                     1
Name: count, Length: 132, dtype: int64

In [56]:
new['gpu'] = (new['gpu']
              .str.replace("®", "", regex=False)
              .str.replace("™", "", regex=False)
              .str.replace("ᵉ", "e", regex=False)
              .str.replace(",", "", regex=False)
              .str.replace(r'\s+', ' ', regex=True)
              .str.strip()
              )
new['gpu'].value_counts()

gpu
Intel UHD Graphics                              52
Integrated Intel UHD Graphics                   22
Integrated                                      12
NVIDIA GeForce RTX 5060 8GB DDR7                11
NVIDIA RTX 4050 6GB                             11
                                                ..
NVIDIA GeForce RTX 3050 / Intel UHD Graphics     1
Intel UHD Graphics 620                           1
RTX 4050                                         1
NVIDIA GeForce MX570 2G                          1
NVIDIA RTX4050 6GB DDR6                          1
Name: count, Length: 125, dtype: int64

In [57]:
procGpu = new['gpu'].copy()
procGpu.value_counts()

gpu
Intel UHD Graphics                              52
Integrated Intel UHD Graphics                   22
Integrated                                      12
NVIDIA GeForce RTX 5060 8GB DDR7                11
NVIDIA RTX 4050 6GB                             11
                                                ..
NVIDIA GeForce RTX 3050 / Intel UHD Graphics     1
Intel UHD Graphics 620                           1
RTX 4050                                         1
NVIDIA GeForce MX570 2G                          1
NVIDIA RTX4050 6GB DDR6                          1
Name: count, Length: 125, dtype: int64

In [58]:
procGpu.sample(35)

43                                   NVIDIA RTX 4050 6GB
323                            NVIDIA Quadro K2100M 2 GB
290                                             P1000-4G
283                                             T1000-4G
273                                  AMD Radeon Graphics
322         NVIDIA GeForce RTX 3050 / Intel UHD Graphics
78                                    Intel UHD Graphics
306                                   NVIDIA RTX5060 8GB
135                NVIDIA GeForce RTX 4060 8GB DDR6 125W
121    NVIDIA GeForce RTX 4050 6GB DDR6 UP to 1605MHz...
213                                   Intel UHD Graphics
1                                     Intel UHD Graphics
13                                   NVIDIA RTX 5060 8GB
180                                   AMD FIREPRO W5170M
107                        Integrated Intel UHD Graphics
147                            Integrated Intel Graphics
136                  NVIDIA GeForce RTX 3070 8GB 130Watt
66                             Integrated Intel Graphics
276                                   Intel UHD Graphics
40                                   NVIDIA RTX 3050 6GB
182                                intel HD graphics 620
45                                   NVIDIA RTX 3050 6GB
239                                   Intel UHD Graphics
62                     Integrated Intel Iris Xe Graphics
109                 NVIDIA GeForce RTX 4060 8GB DDR6 90W
267                                           Integrated
207                                    intel HD graphics
132                NVIDIA GeForce RTX 5070 8GB DDR7 115W
154                        Integrated Intel UHD Graphics
7                                    NVIDIA RTX 3050 4GB
252                                     AMD RADEON 7400M
20                                   NVIDIA RTX 4060 8GB
108               NVIDIA GeForce RTX 4090 16GB DDR6 115W
21                                   NVIDIA RTX 5060 8GB
246                                      NVIDIA RTX 5060
Name: gpu, dtype: object

In [59]:
def extract_gpu_brand(x):
    if not x:
        return "unknown"

    x = str(x).lower()

    # Explicit brands
    if "nvidia" in x:
        return "nvidia"

    if "amd" in x or "radeon" in x:
        return "amd"

    if "intel" in x or "integrated" in x:
        return "intel"

    if "apple" in x:
        return "apple"

    # NVIDIA model keywords
    nvidia_patterns = [
        r'rtx',
        r'gtx',
        r'\bmx\d+',
        r'\bt\d+',
        r'\bp\d+',
        r'\bm\d+',
        r'gt\d+'
    ]

    for pattern in nvidia_patterns:
        if re.search(pattern, x):
            return "nvidia"

    return "unknown"

gpuBrand = procGpu.apply(lambda x: extract_gpu_brand(x))

In [60]:
procGpu[gpuBrand[gpuBrand== 'unknown'].index]

103    ntegrated Qualcomm Adreno GPU
143
204             هارد سوبر سريع SSD⚡️
225              هارد سوبر سريع SSD⚡
324                              NaN
327                       Anti-glare
329                       Anti-glare
Name: gpu, dtype: object

In [61]:
#Nooooote: /s is white space (normal space, /t, /n,....)
def extract_gpu_model(x):
    if not x:
        return "unknown"
    x = str(x).lower()
    gmpattern = [
        r'rtx\s?\d+',
        r'gtx\s?\d+',
        r'mx\s?\d+',
        r'm\s?\d+',
        r't\s?\d+',
        r'p\s?\d+',
        ####AMD####
        r'\d{3,4}[a-z]',
        r'rx\s?\d+',
        r'r\s?\d+',
        r'wx\s?\d+',
        ##apple##
        r'apple\s?\d+',
        ##intel##
        r'iris\s?xe',
        r'uhd',
        r'hd',
        r'arc\s?\d*[a-z]?'
    ]
    for pattern in gmpattern:
        result = re.search(pattern , x)
        if(result):
            return result.group(0)
    return "unknown"

gpuModel = procGpu.apply(lambda x: extract_gpu_model(x))
gpuModel = gpuModel.replace(r'\s', '', regex=True)

In [62]:
gpuModel.value_counts()

gpu
uhd        78
rtx5060    37
unknown    36
rtx4050    26
rtx3050    21
rtx5070    19
rtx5050    18
irisxe     12
hd         10
rtx4060     6
rtx4070     5
mx570       4
t1000       4
610m        3
rtx3070     3
apple10     3
140t        2
rtx3060     2
p620        2
rtx5080     2
rtx4090     2
140v        2
p1000       2
mx130       2
rtx2050     1
mx450       1
rtx3080     1
arc         1
wx4150      1
p3000       1
arcg        1
5170m       1
560x        1
apple14     1
apple8      1
r5          1
rtx3000     1
rtx4000     1
mx250       1
8650g       1
m2200       1
7400m       1
rtx2060     1
m620        1
p600        1
m2000       1
mx330       1
t720        1
t2000       1
m1000       1
p2000       1
p520        1
t600        1
m2          1
Name: count, dtype: int64

In [63]:
"""TODO: I didn't handle the amd radeon rx vega 10 case yet"""

"TODO: I didn't handle the amd radeon rx vega 10 case yet"

In [64]:
procGpu[gpuModel[gpuModel == "unknown"].index]

66          Integrated Intel Graphics
68          Integrated Intel Graphics
79          Integrated Intel Graphics
84          Integrated Intel Graphics
85          Integrated Intel Graphics
103     ntegrated Qualcomm Adreno GPU
143
147         Integrated Intel Graphics
150         Integrated Intel Graphics
151         Integrated Intel Graphics
159    AMD Radeon RX Vega 10 Graphics
174    AMD RADEON RX VAGA 10 GRAPHICS
176            AMD RADEON TM GRAPHICS
179            AMD RADEON TM GRAPHICS
204              هارد سوبر سريع SSD⚡️
221               AMD RADEON Graphics
225               هارد سوبر سريع SSD⚡
241               AMD Radeon Graphics
258               AMD RADEON Graphics
264                        Integrated
266                        Integrated
267                        Integrated
273               AMD Radeon Graphics
277                        Integrated
282                        Integrated
284                        Integrated
299                        Integrated
303                        integrated
308                        Integrated
311                        Integrated
318                        Integrated
319                        Integrated
321                        Integrated
324                               NaN
327                        Anti-glare
329                        Anti-glare
Name: gpu, dtype: object

In [65]:
#Final for Gpu
print(gpuBrand.head(1))
print(gpuModel.head(1))

0    intel
Name: gpu, dtype: object
0    uhd
Name: gpu, dtype: object

# RAM Handling

In [66]:
new['ram'].value_counts()

ram
16GB DDR5-5600MHZ                                 25
16GB DDR5                                         22
8GB DDR4-3200 MHz                                 19
8GB                                               19
الرام:8 غيغا //DDR4 🔥                             18
                                                  ..
4GB                                                1
8G                                                 1
16 GB                                              1
16G DDR4                                           1
8GB DDR4 2666 Mhz                                  1
Name: count, Length: 82, dtype: int64

In [67]:
new['ram'].isna().sum()

np.int64(3)

In [68]:
new.loc[new[new['ram'].isna()].index]

,brand,model,cpu,ram,hard,gpu,new,price,source
328,hp,NaN,Intel Core i5 1334U,NaN,NaN,NVIDIA GeForce MX570 2G,False,560,afandyAndSpahi
329,Lenovo,NaN,Intel i5 13420H,NaN,NaN,Anti-glare,False,480,afandyAndSpahi
330,hp,15-FB2082WM,AMD Ryzen 5,NaN,NaN,NVIDIA RTX4050 6GB DDR6,False,775,afandyAndSpahi

In [69]:
processingRam = new['ram'].copy()
processingRam.value_counts()

ram
16GB DDR5-5600MHZ                                 25
16GB DDR5                                         22
8GB DDR4-3200 MHz                                 19
8GB                                               19
الرام:8 غيغا //DDR4 🔥                             18
                                                  ..
4GB                                                1
8G                                                 1
16 GB                                              1
16G DDR4                                           1
8GB DDR4 2666 Mhz                                  1
Name: count, Length: 82, dtype: int64

In [70]:
def clean_text(x):
    if pd.isna(x):
        return ""
    # keep only English letters, numbers, spaces
    return re.sub(r'[^a-zA-Z0-9\s]', ' ', x)

In [71]:
processingRam = processingRam.apply(lambda x: clean_text(x))
processingRam = processingRam.str.strip()
processingRam.value_counts()

ram
16GB DDR5            34
16GB DDR5 5600MHZ    25
8GB                  21
8        DDR4        20
8GB DDR4 3200 MHz    19
                     ..
4GB                   1
8G                    1
16 GB                 1
16G DDR4              1
8GB DDR4 2666 Mhz     1
Name: count, Length: 69, dtype: int64

In [72]:
def extract_ram_size(x):
    if not x:
        return 0

    x = str(x).lower()

    # 1. GB 
    match = re.search(r'(\d{1,3})\s*gb', x)
    if match:
        return int(match.group(1))

    # 2. G  (8G)
    match = re.search(r'(\d{1,3})\s*g\b', x)
    if match:
        return int(match.group(1))

    # 3. fallback 
    match = re.search(r'\b(\d{1,3})\b', x)
    if match:
        return int(match.group(1))

    return 0

ramSize = processingRam.apply(lambda x: extract_ram_size(x))
print(ramSize.value_counts())
print('='*10)
new['ram'][ramSize[ramSize == 0].index]

ram
16    170
8     108
32     22
4       9
12      9
24      8
0       4
2       1
Name: count, dtype: int64
==========

111
328                                                 NaN
329                                                 NaN
330                                                 NaN
Name: ram, dtype: object

In [73]:
def extract_ram_type(x):
    if  pd.isna(x):
        return "unknown"

    x = x.lower()

    match = re.search(r'ddr\d', x)
    if match:
        return match.group(0)

    match = re.search(r'lpddr\d', x)
    if match:
        return match.group(0)

    return "unknown"

ramType = processingRam.apply(lambda x: extract_ram_type(x))
ramType.value_counts()

ram
ddr5       148
ddr4       115
unknown     65
ddr6         3
Name: count, dtype: int64

In [74]:
#Final for Ram
print(ramSize.head(1))
print(ramType.head(1))

0    8
Name: ram, dtype: int64
0    ddr4
Name: ram, dtype: object

# Storage Handling

In [75]:
procStorage = new['hard'].copy()
procStorage.value_counts()

hard
512GB NVMe PCIe Gen4                   57
512GB SSD NVMe                         41
1TB PCIe® 4.0 NVMe™ M.2                21
الهارد :512 غيغا/SSD/                  21
512GB SSD                              17
الهارد :256 غيغا/SSD/                  15
الهارد :512غيغا/SSD/                   13
512GB SSD M.2 NVMe                     13
الهارد: 256 غيغا/SSD/                  11
1TB SSD NVMe                           11
256GB SSD                               9
256GB NVMe SSD                          8
512GB SSD                               8
SSD الهارد: 1000 غيغا                   6
الهارد: 512 غيغا/SSD/                   6
256GB SSD NVMe                          6
1TB SSD M.2 NVMe                        6
الهارد : 512 غيغا/SSD/                  5
512GB NVMe                              4
256GB SSD NVMe®, PCIe 4.0               3
512GB HDD                               3
الهارد :1000 غيغا/SSD/                  3
الهارد : 1000 غيغا/SSD/                 3
SSD الهارد: 512 غيغا                    3
1TB SSD                                 3
الهارد :256غيغا/SSD/                    2
2TB PCIe® 4.0 NVMe™ M.2 SSD             2
512GB SSD M.2 2242 PCIe® 4.0 NVMe®      2
1TB HDD Sata 2.5"                       2
1T-HDD + 128-SSD-NVME                   1
1TB SSD NVMe,PCI Express 3.0            1
2TB SSD NVMe,PCI Express 3.0 (1 1)      1
1TB-HDD+256GB-SSD-NVME                  1
2TB SSD NVMe                            1
64GB eMMC flash storage                 1
1TB PCIe Gen4 SSD                       1
512GB SSD NVMe,PCI Express 3.0          1
الهارد:250غيغا                          1
الهارد :1 تيرابايت // SSD               1
الهارد: 512غيغا/SSD/                    1
SSD الهارد: 2000 غيغا                   1
256 GB SSD                              1
512GB SSD M.2                           1
128GB SSD                               1
256 GB SSD - NVMe                       1
512GB M.2 NVMe PCIe 4.0 SSD             1
500 GB SSD                              1
512G SSD                                1
500GB                                   1
256GB                                   1
512 GB SSD                              1
NVME 512GB SSD                          1
Name: count, dtype: int64

In [76]:
procStorage = procStorage.apply( lambda x: clean_text(x))
procStorage = procStorage.str.strip()
procStorage.value_counts()

hard
512GB NVMe PCIe Gen4                 57
512GB SSD NVMe                       41
512      SSD                         32
256      SSD                         26
512GB SSD                            25
1TB PCIe  4 0 NVMe  M 2              21
512     SSD                          14
512GB SSD M 2 NVMe                   13
1TB SSD NVMe                         11
256GB SSD                             9
256GB NVMe SSD                        8
1TB SSD M 2 NVMe                      6
SSD         1000                      6
1000      SSD                         6
256GB SSD NVMe                        6
512GB NVMe                            4
                                      4
512GB HDD                             3
1TB SSD                               3
SSD         512                       3
256GB SSD NVMe   PCIe 4 0             3
2TB PCIe  4 0 NVMe  M 2 SSD           2
512GB SSD M 2 2242 PCIe  4 0 NVMe     2
1TB HDD Sata 2 5                      2
256     SSD                           2
1TB SSD NVMe PCI Express 3 0          1
1TB PCIe Gen4 SSD                     1
2TB SSD NVMe                          1
64GB eMMC flash storage               1
1TB HDD 256GB SSD NVME                1
512GB SSD NVMe PCI Express 3 0        1
SSD         2000                      1
250                                   1
1             SSD                     1
1T HDD   128 SSD NVME                 1
2TB SSD NVMe PCI Express 3 0  1 1     1
256 GB SSD                            1
128GB SSD                             1
512GB SSD M 2                         1
256 GB SSD   NVMe                     1
512GB M 2 NVMe PCIe 4 0 SSD           1
512G SSD                              1
500 GB SSD                            1
500GB                                 1
256GB                                 1
512 GB SSD                            1
NVME 512GB SSD                        1
Name: count, dtype: int64

In [77]:
def extract_storage_size(x):
    if not x:
        return 0

    x = str(x).lower()

    # 🔥 TB → 1000 GB
    match = re.search(r'(\d+)\s*tb', x)
    if match:
        return int(match.group(1)) * 1000

    # 🔥 GB (512G / 512GB)
    match = re.search(r'(\d{3,4})\s*g\b', x)
    if match:
        return int(match.group(1))

    match = re.search(r'(\d{3,4})\s*gb', x)
    if match:
        return int(match.group(1))

    # 🔥 fallback (last chance only valid sizes)
    match = re.findall(r'\b(128|256|512|1000|2000|64)\b', x)
    if match:
        return max([int(i) for i in match])

    return 0

storageSize = procStorage.apply(lambda x: extract_storage_size(x))
storageSize.value_counts()

hard
512     200
1000     58
256      57
0         7
2000      5
128       2
500       2
Name: count, dtype: int64

In [78]:
procStorage[storageSize ==0]

98     64GB eMMC flash storage
226          1             SSD
260                        250
324
328
329
330
Name: hard, dtype: object

In [79]:
def extract_storage_type(x):
    if not x:
        return "unknown"

    x = str(x).lower()

    # HDD explicit
    if "hdd" in x:
        return "hdd"

    # SSD explicit
    if "ssd" in x:
        return "ssd"

    # implicit SSD indicators
    if any(k in x for k in ["nvme", "m.2", "pcie", "emmc"]):
        return "ssd"

    return "unknown"
storageType = procStorage.apply(lambda x: extract_storage_type(x))
storageType.value_counts()

hard
ssd        317
hdd          7
unknown      7
Name: count, dtype: int64

In [80]:
procStorage[storageType == "unknown"]

260      250
323    500GB
324
325    256GB
328
329
330
Name: hard, dtype: object

In [81]:
#Final for Storage
print(storageSize.head(1))
print(storageType.head(1))

0    256
Name: hard, dtype: int64
0    ssd
Name: hard, dtype: object

# Processing the new extracted specs with dataset

In [82]:
processed_df = new.copy()
processed_df.drop(columns=['cpu', 'ram', 'hard', 'gpu'], inplace=True)
processed_df['cpu_brand'] = cpuBrand
processed_df['cpu_tier'] = cpuTier
processed_df['cpu_model'] = cpuModel
processed_df['cpu_suffix'] = cpuSuffix
processed_df['gpu_brand'] = gpuBrand
processed_df['gpu_model'] = gpuModel
processed_df['ram_size'] = ramSize
processed_df['ram_type'] = ramType
processed_df['storage_size'] = storageSize
processed_df['storage_type'] = storageType

In [83]:
processed_df = new.copy()
processed_df.drop(columns=['cpu', 'ram', 'hard', 'gpu'], inplace=True)
processed_df['cpu_brand'] = cpuBrand
processed_df['cpu_tier'] = cpuTier
processed_df['cpu_model'] = cpuModel
processed_df['cpu_suffix'] = cpuSuffix
processed_df['gpu_brand'] = gpuBrand
processed_df['gpu_model'] = gpuModel
processed_df['ram_size'] = ramSize
processed_df['ram_type'] = ramType
processed_df['storage_size'] = storageSize
processed_df['storage_type'] = storageType

In [84]:
processed_df

,brand,model,new,price,source,cpu_brand,cpu_tier,cpu_model,cpu_suffix,gpu_brand,gpu_model,ram_size,ram_type,storage_size,storage_type
0,ASUS,ASUS Vivobook E1504G,true,335,spacenet,intel,i3,305,unknown,intel,uhd,8,ddr4,256,ssd
1,ASUS,ASUS VivoBook 15 X1504VA‑NJ739,true,360,spacenet,intel,i3,1315,u,intel,uhd,8,ddr4,512,ssd
2,ASUS,ASUS ExpertBook,true,355,spacenet,intel,i3,1315,u,intel,uhd,8,ddr5,256,ssd
3,ASUS,ASUS Vivobook X1404V,true,465,spacenet,amd,ryzen 7,7445,hs,nvidia,rtx4050,16,ddr5,512,ssd
4,ASUS,ASUS Vivobook 15 X1504VA‑NJ104,true,465,spacenet,intel,i5,1335,u,intel,uhd,8,ddr4,512,ssd
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
326,Lenovo,LOQ 15IAX9E,True,840,afandyAndSpahi,None,i7,12650,hx,nvidia,rtx4050,16,ddr5,512,ssd
327,Dell,Vostro 3530,True,470,afandyAndSpahi,intel,i5,1334,u,unknown,unknown,8,ddr4,512,ssd
328,hp,NaN,False,560,afandyAndSpahi,intel,i5,1334,u,nvidia,mx570,0,unknown,0,unknown
329,Lenovo,NaN,False,480,afandyAndSpahi,intel,i5,13420,h,unknown,unknown,0,unknown,0,unknown
330,hp,15-FB2082WM,False,775,afandyAndSpahi,amd,ryzen 5,0,unknown,nvidia,rtx4050,0,unknown,0,unknown

In [85]:
processed_df.isna().sum()

brand            0
model            2
new              0
price            0
source           0
cpu_brand       14
cpu_tier         0
cpu_model        0
cpu_suffix       0
gpu_brand        0
gpu_model        0
ram_size         0
ram_type         0
storage_size     0
storage_type     0
dtype: int64

In [86]:
processed_df['cpu_brand'] = processed_df['cpu_brand'].fillna(processed_df['cpu_brand'].mode()[0])
processed_df['model'] = processed_df['model'].fillna(processed_df['model'].mode()[0])

In [87]:
processed_df.isna().sum()

brand           0
model           0
new             0
price           0
source          0
cpu_brand       0
cpu_tier        0
cpu_model       0
cpu_suffix      0
gpu_brand       0
gpu_model       0
ram_size        0
ram_type        0
storage_size    0
storage_type    0
dtype: int64

In [88]:
processed_df.duplicated().sum()

np.int64(1)

In [89]:
processed_df = processed_df.drop_duplicates()

In [90]:
processed_df

,brand,model,new,price,source,cpu_brand,cpu_tier,cpu_model,cpu_suffix,gpu_brand,gpu_model,ram_size,ram_type,storage_size,storage_type
0,ASUS,ASUS Vivobook E1504G,true,335,spacenet,intel,i3,305,unknown,intel,uhd,8,ddr4,256,ssd
1,ASUS,ASUS VivoBook 15 X1504VA‑NJ739,true,360,spacenet,intel,i3,1315,u,intel,uhd,8,ddr4,512,ssd
2,ASUS,ASUS ExpertBook,true,355,spacenet,intel,i3,1315,u,intel,uhd,8,ddr5,256,ssd
3,ASUS,ASUS Vivobook X1404V,true,465,spacenet,amd,ryzen 7,7445,hs,nvidia,rtx4050,16,ddr5,512,ssd
4,ASUS,ASUS Vivobook 15 X1504VA‑NJ104,true,465,spacenet,intel,i5,1335,u,intel,uhd,8,ddr4,512,ssd
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
326,Lenovo,LOQ 15IAX9E,True,840,afandyAndSpahi,intel,i7,12650,hx,nvidia,rtx4050,16,ddr5,512,ssd
327,Dell,Vostro 3530,True,470,afandyAndSpahi,intel,i5,1334,u,unknown,unknown,8,ddr4,512,ssd
328,hp,15IRX9,False,560,afandyAndSpahi,intel,i5,1334,u,nvidia,mx570,0,unknown,0,unknown
329,Lenovo,15IRX9,False,480,afandyAndSpahi,intel,i5,13420,h,unknown,unknown,0,unknown,0,unknown
330,hp,15-FB2082WM,False,775,afandyAndSpahi,amd,ryzen 5,0,unknown,nvidia,rtx4050,0,unknown,0,unknown

In [91]:
processed_df.dtypes

brand           object
model           object
new             object
price            int64
source          object
cpu_brand       object
cpu_tier        object
cpu_model        int64
cpu_suffix      object
gpu_brand       object
gpu_model       object
ram_size         int64
ram_type        object
storage_size     int64
storage_type    object
dtype: object

In [92]:
processed_df['new'] = (
    processed_df['new']
    .astype(str)
    .str.lower()
    .str.strip()
)

processed_df['new'] = processed_df['new'].map({
    'true': 1,
    'false': 0
}).astype(int)

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_16340\375509808.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  processed_df['new'] = (
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_16340\375509808.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  processed_df['new'] = processed_df['new'].map({

In [93]:
processed_df['new'].value_counts()

new
1    259
0     71
Name: count, dtype: int64

In [94]:
processed_df.dtypes

brand           object
model           object
new              int64
price            int64
source          object
cpu_brand       object
cpu_tier        object
cpu_model        int64
cpu_suffix      object
gpu_brand       object
gpu_model       object
ram_size         int64
ram_type        object
storage_size     int64
storage_type    object
dtype: object

# Encode the Data

In [95]:
processed_df.columns

Index(['brand', 'model', 'new', 'price', 'source', 'cpu_brand', 'cpu_tier',
       'cpu_model', 'cpu_suffix', 'gpu_brand', 'gpu_model', 'ram_size',
       'ram_type', 'storage_size', 'storage_type'],
      dtype='object')

In [96]:
processed_df['gpu_model'].unique()

array(['uhd', 'rtx4050', 'rtx3050', 'rtx5050', 'rtx5060', 'rtx5070',
       'rtx4060', 'mx570', 'rtx2050', 'irisxe', '610m', 'mx450', '140v',
       'unknown', 'arc', 'rtx3070', 'rtx3060', 'rtx4090', 'rtx4070',
       'rtx5080', 'rtx3080', '140t', 'rtx4000', 'rtx3000', 'p620',
       'wx4150', 'p3000', 'hd', '5170m', 'arcg', 't1000', '560x',
       'apple10', 'apple14', 'apple8', 'r5', '8650g', 'mx250', '7400m',
       'm2200', 'mx130', 'm2000', 'rtx2060', 'm620', 'p600', 'mx330',
       't720', 'p1000', 't2000', 'm1000', 'p2000', 'p520', 't600', 'm2'],
      dtype=object)

In [97]:
processed_df = processed_df.drop(
    columns=['model', 'source']
)
categorical_cols = [
    'brand',
    'cpu_brand',
    'cpu_tier',
    'cpu_suffix',
    'gpu_brand',
    'gpu_model',
    'ram_type',
    'storage_type'
]
ml_df = pd.get_dummies(
    processed_df,
    columns=categorical_cols,
    drop_first=True
)

In [98]:
ml_df.shape

(330, 115)

In [99]:
ml_df.dtypes.value_counts()

bool     110
int64      5
Name: count, dtype: int64

In [100]:
bool_cols = ml_df.select_dtypes(include='bool').columns
ml_df[bool_cols] = ml_df[bool_cols].astype(int)

ml_df.dtypes.value_counts()

int64    115
Name: count, dtype: int64

In [101]:
ml_df.head()

,new,price,cpu_model,ram_size,storage_size,brand_APPLE,brand_ASUS,brand_Dell,brand_Lenovo,brand_MSI,...,gpu_model_t600,gpu_model_t720,gpu_model_uhd,gpu_model_unknown,gpu_model_wx4150,ram_type_ddr5,ram_type_ddr6,ram_type_unknown,storage_type_ssd,storage_type_unknown
0,1,335,305,8,256,0,1,0,0,0,...,0,0,1,0,0,0,0,0,1,0
1,1,360,1315,8,512,0,1,0,0,0,...,0,0,1,0,0,0,0,0,1,0
2,1,355,1315,8,256,0,1,0,0,0,...,0,0,1,0,0,1,0,0,1,0
3,1,465,7445,16,512,0,1,0,0,0,...,0,0,0,0,0,1,0,0,1,0
4,1,465,1335,8,512,0,1,0,0,0,...,0,0,1,0,0,0,0,0,1,0

In [102]:
processed_df.select_dtypes(include=['int64', 'float64']).corr()

                   new     price  cpu_model  ram_size  storage_size
new           1.000000  0.397678   0.072053  0.133834      0.285045
price         0.397678  1.000000   0.072520  0.653001      0.732343
cpu_model     0.072053  0.072520   1.000000  0.117095     -0.014060
ram_size      0.133834  0.653001   0.117095  1.000000      0.574420
storage_size  0.285045  0.732343  -0.014060  0.574420      1.000000

# ML training

In [103]:
# Linear regression
X = ml_df.drop('price', axis=1)
y = ml_df['price']

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42
)

In [104]:
import joblib
joblib.dump(X.columns.tolist(), "training_columns.pkl")

['training_columns.pkl']

In [105]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()

In [106]:
model.fit(X_train, y_train)

LinearRegression()

In [107]:
pred = model.predict(X_test)

In [108]:
from sklearn.metrics import (
    mean_absolute_error,
    r2_score
)

print("MAE:", mean_absolute_error(y_test, pred))
print("R2:", r2_score(y_test, pred))

MAE: 96.84493486864646
R2: 0.9004756922147827

In [109]:
print(pred[:10])
print('*'*10)
print(y_test[:10])

[ 874.70717147  345.01278314  882.6671243   969.80003953  460.7631579
 1150.78790168  502.24265865  369.90189887  747.57854804  618.75976136]
**********
9       910
164     475
139     895
46      975
94      475
101    1370
84      575
312     400
317     500
220     570
Name: price, dtype: int64

In [110]:
results = pd.DataFrame({
    'actual': y_test,
    'predicted': pred
})

results['error'] = abs(
    results['actual'] - results['predicted']
)

results.sort_values('error', ascending=False)

     actual   predicted       error
311     175  632.365379  457.365379
3       465  834.311040  369.311040
307     450  730.727629  280.727629
78      750  481.187500  268.812500
298     300  568.220556  268.220556
..      ...         ...         ...
33      320  330.444439   10.444439
257     500  490.255083    9.744917
77      490  481.187500    8.812500
46      975  969.800040    5.199960
140     935  936.914608    1.914608

[66 rows x 3 columns]

In [111]:
coef_df = pd.DataFrame({
    'feature': X.columns,
    'coef': model.coef_
})

coef_df.sort_values('coef', ascending=False)

               feature         coef
101  gpu_model_rtx5080  1961.259886
97   gpu_model_rtx4090  1916.249955
96   gpu_model_rtx4070   564.589000
4          brand_APPLE   539.830790
58      gpu_model_560x   485.924086
..                 ...          ...
84      gpu_model_p620  -379.901768
59      gpu_model_610m  -386.757775
103    gpu_model_t2000  -426.777211
105     gpu_model_t720  -513.810739
70        gpu_model_m2  -869.992264

[114 rows x 2 columns]

In [112]:
processed_df['gpu_model'].value_counts()

gpu_model
uhd        78
rtx5060    37
unknown    36
rtx4050    26
rtx3050    21
rtx5070    19
rtx5050    18
irisxe     12
hd          9
rtx4060     6
rtx4070     5
mx570       4
t1000       4
610m        3
rtx3070     3
apple10     3
140t        2
rtx3060     2
p620        2
rtx5080     2
rtx4090     2
140v        2
p1000       2
mx130       2
rtx2050     1
mx450       1
rtx3080     1
arc         1
wx4150      1
p3000       1
arcg        1
5170m       1
560x        1
apple14     1
apple8      1
r5          1
rtx3000     1
rtx4000     1
mx250       1
8650g       1
m2200       1
7400m       1
rtx2060     1
m620        1
p600        1
m2000       1
mx330       1
t720        1
t2000       1
m1000       1
p2000       1
p520        1
t600        1
m2          1
Name: count, dtype: int64

Random Forest

In [113]:
from sklearn.ensemble import RandomForestRegressor

rf = RandomForestRegressor(
    n_estimators=100,
    random_state=42
)

rf.fit(X_train, y_train)

RandomForestRegressor(random_state=42)

In [114]:
pred_rf = rf.predict(X_test)

In [115]:
print("MAE: ",mean_absolute_error(y_test, pred_rf))
print("R2:",r2_score(y_test, pred_rf))

MAE:  83.71078703703702
R2: 0.9089529335245727

In [116]:
importance_df = pd.DataFrame({
    'feature': X.columns,
    'importance': rf.feature_importances_
})

importance_df.sort_values(
    'importance',
    ascending=False
)

               feature  importance
3         storage_size    0.356165
2             ram_size    0.151249
54    gpu_brand_nvidia    0.064800
0                  new    0.059100
97   gpu_model_rtx4090    0.053928
..                 ...         ...
73      gpu_model_m620    0.000000
81     gpu_model_p3000    0.000000
82      gpu_model_p520    0.000000
104     gpu_model_t600    0.000000
108   gpu_model_wx4150    0.000000

[114 rows x 2 columns]

In [117]:
processed_df.to_csv(
    'processed_laptops.csv',
    index=False
)
###############################
ml_df.to_csv(
    'ml_laptops.csv',
    index=False
)

In [118]:
from catboost  import CatBoostRegressor
from sklearn.metrics import (
    mean_absolute_error,
    r2_score
)

cb = CatBoostRegressor(
    iterations=500,
    learning_rate=0.05,
    depth=6,
    verbose=0,
    random_state=42
)

cb.fit(X_train, y_train)

pred_cb = cb.predict(X_test)

print(mean_absolute_error(y_test, pred_cb))
print(r2_score(y_test, pred_cb))

ModuleNotFoundError: No module named 'catboost'

# For Del

In [153]:
zero_row = pd.DataFrame([np.zeros(len(X.columns))], columns=X.columns)
test_sample = zero_row.copy()

test_sample['ram_size'] = 16
test_sample['gpu_brand_nvidia'] = 1
test_sample['brand_Lenovo'] = 1
test_sample['storage_type_ssd'] = 1
test_sample['cpu_model']= 9750
test_sample['cpu_suffix_h'] = 1
test_sample['cpu_tier_i7'] = 1
test_sample['cpu_brand_intel'] = 1
test_sample['storage_size'] = 256
test_sample['new'] = 0
test_sample['gpu_model_unknown'] = 1

print(rf.predict(test_sample))

[362.35]

In [144]:
test_sample

,new,cpu_model,ram_size,storage_size,brand_APPLE,brand_ASUS,brand_Dell,brand_Lenovo,brand_MSI,brand_Microsoft,...,gpu_model_t600,gpu_model_t720,gpu_model_uhd,gpu_model_unknown,gpu_model_wx4150,ram_type_ddr5,ram_type_ddr6,ram_type_unknown,storage_type_ssd,storage_type_unknown
0,0,9750,16,256,0.0,0.0,0.0,1,0.0,0.0,...,0.0,0.0,0.0,1,0.0,0.0,0.0,0.0,1,0.0

In [154]:
new.loc[182]

brand                                    Dell
model     DELL 5580/i5-73000U
cpu              intel core i5 73000U 2 60ghz
ram         الرام: 8 غيغا/DDR4/
hard               الهارد: 256 غيغا/SSD/
gpu                     intel HD graphics 620
new                                    false
price                                     185
source                               laptopSy
Name: 182, dtype: object